// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { UsiCat$Type } from "./UsiCat";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["UsiCat"]: UsiCat$Type;
    ["contracts/UsiCat.sol:UsiCat"]: UsiCat$Type;
  }

  interface ContractTypesMap {
    ["UsiCat"]: GetContractReturnType<UsiCat$Type["abi"]>;
    ["contracts/UsiCat.sol:UsiCat"]: GetContractReturnType<UsiCat$Type["abi"]>;
  }
}
